<option value="">Pick Residence / District</option>
<option value="Baringo">Baringo</option>
<option value="Bomet">Bomet</option>
<option value="Bondo">Bondo</option>
<option value="Bungoma">Bungoma</option>
<option value="Buret">Buret</option>
<option value="Busia">Busia</option>
<option value="Butere/Mumias">Butere/Mumias</option>
<option value="Embu">Embu</option>
<option value="Gatundu">Gatundu</option>
<option value="Garissa">Garissa</option>
<option value="Gucha">Gucha</option>
<option value="Homa Bay">Homa Bay</option>
<option value="Ijara">Ijara</option>
<option value="Isiolo">Isiolo</option>
<option value="Kajiado">Kajiado</option>
<option value="Kakamega">Kakamega</option>
<option value="Keiyo">Keiyo</option>
<option value="Kericho">Kericho</option>
<option value="Kiambu">Kiambu</option>
<option value="Kilifi">Kilifi</option>
<option value="Kirinyaga">Kirinyaga</option>
<option value="Kisii Central">Kisii Central</option>
<option value="Kisumu">Kisumu</option>
<option value="Kitui">Kitui</option>
<option value="Koibatek">Koibatek</option>
<option value="Kuria">Kuria</option>
<option value="Kwale">Kwale</option>
<option value="Laikipia">Laikipia</option>
<option value="Lamu">Lamu</option>
<option value="Limuru">Limuru</option>
<option value="Lugari">Lugari</option>
<option value="Machakos">Machakos</option>
<option value="Makueni">Makueni</option>
<option value="Malindi">Malindi</option>
<option value="Mandera">Mandera</option>
<option value="Maragua">Maragua</option>
<option value="Marakwet">Marakwet</option>
<option value="Marsabit">Marsabit</option>
<option value="Mbeere">Mbeere</option>
<option value="Meru Central">Meru Central</option>
<option value="Meru North">Meru North</option>
<option value="Meru South">Meru South</option>
<option value="Migori">Migori</option>
<option value="Mombasa">Mombasa</option>
<option value="Mount Elgon">Mount Elgon</option>
<option value="Murang'a">Murang'a</option>
<option value="Mwingi">Mwingi</option>
<option value="Nairobi">Nairobi</option>
<option value="Nakuru">Nakuru</option>
<option value="Nandi">Nandi</option>
<option value="Narok">Narok</option>
<option value="Ngong">Ngong'</option>
<option value="Nyahururu">Nyahururu</option>
<option value="Nyamira">Nyamira</option>
<option value="Nyandarua">Nyandarua</option>
<option value="Nyando">Nyando</option>
<option value="Nyeri">Nyeri</option>
<option value="Rachuonyo">Rachuonyo</option>
<option value="Samburu">Samburu</option>
<option value="Siaya">Siaya</option>
<option value="Suba">Suba</option>
<option value="Taita Taveta">Taita Taveta</option>
<option value="Tana River">Tana River</option>
<option value="Teso">Teso</option>
<option value="Tharaka">Tharaka</option>
<option value="Thika">Thika</option>
<option value="Trans Mara">Trans Mara</option>
<option value="Trans Nzoia">Trans Nzoia</option>
<option value="Turkana">Turkana</option>
<option value="Uasin Gishu">Uasin Gishu</option>
<option value="Vihiga">Vihiga</option>
<option value="Wajir">Wajir</option>
<option value="West Pokot">West Pokot</option>
